import assert from 'node:assert/strict';
import { renderMarkdown } from './parser.mjs';
const has = (markdown, pattern) => assert.match(renderMarkdown(markdown), pattern);
has('[OpenAI](https://openai.com)', /href="https:\/\/openai.com"/);
has('https://openai.com', /href="https:\/\/openai.com"/);
has('[reference][docs]\n\n[docs]: https://example.com "Docs"', /href="https:\/\/example.com" title="Docs"/);
has('[file](/tmp/test.swift:12)', /href="\/tmp\/test.swift:12"/);
has('[file](src/main.swift#L20)', /href="src\/main.swift#L20"/);
has('**bold** *italic* ~~deleted~~ `code`', /<strong>bold<\/strong> <em>italic<\/em> <s>deleted<\/s> <code>code<\/code>/);
has('Title\n=====\n\n## Second', /<h1>Title<\/h1>[\s\S]*<h2>Second/);
has('- outer\n  - inner\n\n    continuation', /<ul>[\s\S]*<ul>[\s\S]*continuation/);
has('3. three\n4. four', /<ol start="3">/);
has('- [x] done\n- [ ] todo', /checked=""[\s\S]*todo/);
has('> outer\n> > nested', /<blockquote>[\s\S]*<blockquote>/);
has('| A | B |\n| :--- | ---: |\n| x\\|y | `a` |', /text-align:right[\s\S]*x\|y/);
has('```swift\nlet x = 1\n```', /data-copy[\s\S]*hljs-keyword/);
has('````\n```\n````', /<code>```/);
has('```js\nconst x', /<code class="language-js">/);
has('    code\n    indented', /<pre><code>code\nindented/);
has('Text  \nnext\n\n---', /<br>[\s\S]*<hr>/);
has('A footnote[^1]\n\n[^1]: Explanation', /footnote-ref[\s\S]*Explanation/);
has('![alt](https://example.com/image.png)', /class="image-link"/);
assert.doesNotMatch(renderMarkdown('![alt](https://example.com/image.png)'), /<img/);
has('<script>alert(1)</script>', /&lt;script&gt;/);
assert.doesNotMatch(renderMarkdown('[x](javascript:alert(1))'), /href=/);
has('```mermaid\ngraph TD; A-->B\n```', /class="diagram"/);
has('$$\\frac{1}{2}$$', /katex-display/);
has('Inline \\(x^2\\) and $x+y$', /class="katex"/);
assert.doesNotMatch(renderMarkdown('Costs $5 and $10'), /class="katex"/);
console.log('26 Markdown rendering fixtures passed');
